#!/usr/bin/env bash
# BioBase CS2 Server — One-Click Install
# Installs and starts the full BioBase CS2 server stack (game server + admin dashboard).
# Requirements: Docker + Docker Compose v2
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${SCRIPT_DIR}/bb_cs2_server/docker-compose.yml"
ENV_FILE="${SCRIPT_DIR}/bb_cs2_server/.env"
CLIPS_DIR="${SCRIPT_DIR}/data/clips"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}${BOLD}[biobase]${NC} $*"; }
ok()    { echo -e "${GREEN}${BOLD}[biobase]${NC} $*"; }
die()   { echo -e "${RED}${BOLD}[biobase]${NC} $*" >&2; exit 1; }

echo
echo -e "${BOLD}  ╔══════════════════════════════════════╗${NC}"
echo -e "${BOLD}  ║     BioBase CS2 Server Installer     ║${NC}"
echo -e "${BOLD}  ╚══════════════════════════════════════╝${NC}"
echo

# ── Prerequisites ──

if ! command -v docker >/dev/null 2>&1; then
    die "Docker is not installed. Install it from https://docs.docker.com/get-docker/"
fi

if ! docker info >/dev/null 2>&1; then
    die "Docker daemon is not running or you lack permissions. Try: sudo usermod -aG docker \$USER"
fi

if ! docker compose version >/dev/null 2>&1; then
    die "Docker Compose v2 is required. Install it from https://docs.docker.com/compose/install/"
fi

if [[ ! -f "${COMPOSE_FILE}" ]]; then
    die "Missing ${COMPOSE_FILE}. Run this script from the biobase repository root."
fi

if [[ ! -d "${SCRIPT_DIR}/bb_cs2_dashboard" ]]; then
    die "Missing bb_cs2_dashboard/ directory. Clone the full biobase repository."
fi

ok "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"
ok "Docker Compose $(docker compose version --short)"
echo

# ── Configuration ──

if [[ -f "${ENV_FILE}" ]]; then
    info "Existing .env found at ${ENV_FILE}"
    read -rp "  Overwrite with fresh config? [y/N] " overwrite
    if [[ ! "${overwrite}" =~ ^[Yy]$ ]]; then
        info "Keeping existing .env — skipping config prompts"
        SKIP_CONFIG=1
    else
        SKIP_CONFIG=0
    fi
else
    SKIP_CONFIG=0
fi

if [[ "${SKIP_CONFIG}" -eq 0 ]]; then
    info "Configure your server (press Enter for defaults):"
    echo

    read -rp "  Server name [Biobase CS2]: " input_name
    CS2_SERVERNAME="${input_name:-Biobase CS2}"

    read -rp "  RCON password [biobase]: " input_rcon
    CS2_RCONPW="${input_rcon:-biobase}"

    read -rp "  Dashboard password [biobase]: " input_dash
    BB_CS2_DASHBOARD_TOKEN="${input_dash:-biobase}"

    read -rp "  Starting map [de_mirage]: " input_map
    CS2_STARTMAP="${input_map:-de_mirage}"

    echo

    cat > "${ENV_FILE}" <<ENVEOF
# BioBase CS2 Server — generated by install.sh
# Edit and restart: docker compose -f bb_cs2_server/docker-compose.yml up -d

# ── Server ──
CS2_SERVERNAME=${CS2_SERVERNAME}
CS2_RCONPW=${CS2_RCONPW}
CS2_STARTMAP=${CS2_STARTMAP}
CS2_MAXPLAYERS=16
CS2_BOT_QUOTA=10
CS2_BOT_DIFFICULTY=1

# Steam Game Server Token (optional — required for public server listing)
# Get one at https://steamcommunity.com/dev/managegameservers
# SRCDS_TOKEN=

# ── Dashboard ──
BB_CS2_DASHBOARD_TOKEN=${BB_CS2_DASHBOARD_TOKEN}

# ── Clips Storage ──
BB_CLIPS_HOST_DIR=${CLIPS_DIR}

# ── Client Connection ──
# Hostname/IP that the BioBase desktop app uses to connect to this server.
# Set to your LAN IP or public IP if clients connect remotely.
BB_CS2_CONNECT_HOST=localhost
BB_CS2_CONNECT_PORT=27015
ENVEOF

    ok "Config written to ${ENV_FILE}"
fi

# ── Create directories ──

mkdir -p "${CLIPS_DIR}"

# ── Build ──

info "Building containers (this takes a few minutes on first run)..."
echo
docker compose -f "${COMPOSE_FILE}" build
echo
ok "Build complete"

# ── Start ──

info "Starting BioBase CS2 server stack..."
docker compose -f "${COMPOSE_FILE}" up -d
echo

# ── Health check ──

info "Waiting for CS2 server to become ready..."
info "(First run downloads ~30 GB of CS2 server files via SteamCMD — this can take 10-30 minutes)"
echo

HOST="127.0.0.1"
PORT="27015"
TIMEOUT=600
ELAPSED=0
INTERVAL=5

while ! timeout 2 bash -c "echo >/dev/tcp/${HOST}/${PORT}" 2>/dev/null; do
    ELAPSED=$((ELAPSED + INTERVAL))
    if [[ ${ELAPSED} -ge ${TIMEOUT} ]]; then
        echo
        die "Timed out waiting for CS2 server on ${HOST}:${PORT} after ${TIMEOUT}s"
    fi
    printf "\r  Waiting... %ds elapsed" "${ELAPSED}"
    sleep "${INTERVAL}"
done

echo
echo
ok "CS2 server is ready!"
echo

# ── Connection info ──

DASH_PORT=$(docker compose -f "${COMPOSE_FILE}" port bb_cs2_dashboard 8780 2>/dev/null | cut -d: -f2 || echo "8780")

echo -e "${BOLD}  ┌──────────────────────────────────────────┐${NC}"
echo -e "${BOLD}  │         BioBase CS2 Server Ready          │${NC}"
echo -e "${BOLD}  ├──────────────────────────────────────────┤${NC}"
echo -e "  │  Game server:  ${CYAN}localhost:27015${NC}          │"
echo -e "  │  Dashboard:    ${CYAN}http://localhost:${DASH_PORT}/admin${NC} │"
echo -e "  │  RCON:         ${CYAN}localhost:27015${NC}          │"
echo -e "${BOLD}  └──────────────────────────────────────────┘${NC}"
echo
info "Manage:"
echo "  Start bots:   ./bb_cs2_server/bots_start.sh"
echo "  Stop bots:    ./bb_cs2_server/bots_stop.sh"
echo "  Stop server:  ./bb_cs2_server/server_stop.sh"
echo "  Start server: ./bb_cs2_server/server_up.sh"
echo "  Verify:       ./bb_cs2_server/verify.sh"
echo "  RCON:         ./bb_cs2_server/rcon.sh status"
echo
