package main

import (
	"archive/zip"
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

//go:embed server.zip
var serverZip []byte

const banner = `
  =============================
   BioBase CS2 Server Setup
  =============================
`

func main() {
	fmt.Println(banner)

	installDir := defaultInstallDir()
	fmt.Printf("  Install location: %s\n\n", installDir)

	// Config
	serverName := prompt("  Server name", "BioBase CS2")
	rconPw := prompt("  RCON password", randomPassword())
	dashPw := prompt("  Dashboard password", randomPassword())
	startMap := prompt("  Starting map", "de_mirage")

	fmt.Println()
	status("Extracting server files...")
	if err := extractZip(serverZip, installDir); err != nil {
		fatal("Failed to extract: %v", err)
	}
	ok("Files extracted")

	// Write .env
	envPath := filepath.Join(installDir, "bb_cs2_server", ".env")
	writeEnv(envPath, serverName, rconPw, dashPw, startMap)
	ok("Configuration saved")

	// Create data/clips
	os.MkdirAll(filepath.Join(installDir, "data", "clips"), 0o755)

	// Docker check
	if !dockerAvailable() {
		status("Docker not found — downloading Docker Desktop...")
		if err := installDocker(); err != nil {
			fmt.Println()
			fmt.Println("  Docker Desktop must be installed manually:")
			fmt.Println("  https://www.docker.com/products/docker-desktop/")
			fmt.Println()
			fmt.Println("  After installing Docker, run this setup again.")
			waitExit()
			return
		}
	}

	if !dockerRunning() {
		status("Waiting for Docker engine...")
		if !waitForDocker(120) {
			fmt.Println("\n  Docker is not running. Start Docker Desktop, then run setup again.")
			waitExit()
			return
		}
	}
	ok("Docker is ready")

	// Build and start
	fmt.Println()
	status("Building and starting containers...")
	status("First run downloads ~30 GB of CS2 server files. Do not close this window.")
	fmt.Println()

	composeFile := filepath.Join(installDir, "bb_cs2_server", "docker-compose.yml")
	cmd := exec.Command("docker", "compose", "-f", composeFile, "up", "-d", "--build")
	cmd.Dir = filepath.Join(installDir, "bb_cs2_server")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fmt.Printf("\n  Build failed: %v\n", err)
		fmt.Println("  Make sure Docker Desktop is running and try again.")
		waitExit()
		return
	}

	ok("Containers started")

	// Health check
	status("Waiting for CS2 server to accept connections...")
	ready := waitForPort("127.0.0.1:27015", 600)

	fmt.Println()
	fmt.Println("  ========================================")
	fmt.Println("    BioBase CS2 Server is running!")
	fmt.Println("  ========================================")
	fmt.Println()
	fmt.Printf("    Game server:  localhost:27015\n")
	fmt.Printf("    Dashboard:    http://localhost:8780/admin\n")
	fmt.Printf("    RCON password: %s\n", rconPw)
	fmt.Printf("    Dashboard password: %s\n", dashPw)
	fmt.Println()
	if !ready {
		fmt.Println("    (Server may still be downloading CS2 files)")
	}

	waitExit()
}

func defaultInstallDir() string {
	home, _ := os.UserHomeDir()
	if home == "" {
		home = "C:\\"
	}
	return filepath.Join(home, "BioBase", "CS2Server")
}

func prompt(label, defaultVal string) string {
	fmt.Printf("%s [%s]: ", label, defaultVal)
	var input string
	fmt.Scanln(&input)
	input = strings.TrimSpace(input)
	if input == "" {
		return defaultVal
	}
	return input
}

func randomPassword() string {
	const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	b := make([]byte, 16)
	f, err := os.Open("/dev/urandom")
	if err != nil {
		// Fallback for Windows
		t := time.Now().UnixNano()
		for i := range b {
			t = t*6364136223846793005 + 1442695040888963407
			b[i] = chars[int(t>>33)%len(chars)]
		}
		return string(b)
	}
	defer f.Close()
	f.Read(b)
	for i := range b {
		b[i] = chars[int(b[i])%len(chars)]
	}
	return string(b)
}

func writeEnv(path, serverName, rconPw, dashPw, startMap string) {
	content := fmt.Sprintf(`# BioBase CS2 Server — generated by installer
CS2_SERVERNAME=%s
CS2_RCONPW=%s
CS2_STARTMAP=%s
CS2_MAXPLAYERS=16
CS2_LAN=0
CS2_CHEATS=0
CS2_BOT_QUOTA=10
CS2_BOT_QUOTA_MODE=fill
CS2_BOT_DIFFICULTY=1
BB_CS2_SERVER_PROFILE=play
BB_CS2_ENABLE_MATCHZY=1
BB_CS2_DASHBOARD_TOKEN=%s
BB_DASHBOARD_ROOT_PATH=/admin
BB_DASHBOARD_COOKIE_SECURE=0
BB_CLIPS_HOST_DIR=./data/clips
BB_CS2_CONNECT_HOST=localhost
BB_CS2_CONNECT_PORT=27015
BB_CLIENT_PAIRING_CODE=BIOBASE-TRY
`, serverName, rconPw, startMap, dashPw)
	os.MkdirAll(filepath.Dir(path), 0o755)
	os.WriteFile(path, []byte(content), 0o644)
}

func extractZip(data []byte, dest string) error {
	r, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		return err
	}
	for _, f := range r.File {
		target := filepath.Join(dest, f.Name)
		if !strings.HasPrefix(filepath.Clean(target), filepath.Clean(dest)) {
			continue // zip slip protection
		}
		if f.FileInfo().IsDir() {
			os.MkdirAll(target, 0o755)
			continue
		}
		os.MkdirAll(filepath.Dir(target), 0o755)
		rc, err := f.Open()
		if err != nil {
			return err
		}
		out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, f.Mode())
		if err != nil {
			rc.Close()
			return err
		}
		io.Copy(out, rc)
		out.Close()
		rc.Close()
	}
	return nil
}

func dockerAvailable() bool {
	cmd := exec.Command("docker", "version")
	return cmd.Run() == nil
}

func dockerRunning() bool {
	cmd := exec.Command("docker", "info")
	return cmd.Run() == nil
}

func installDocker() error {
	if runtime.GOOS != "windows" {
		return fmt.Errorf("auto-install only supported on Windows")
	}
	// Download Docker Desktop installer
	ps := `
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$url = 'https://desktop.docker.com/win/main/amd64/Docker Desktop Installer.exe'
$out = Join-Path $env:TEMP 'DockerDesktopInstaller.exe'
Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing
Start-Process -FilePath $out -ArgumentList 'install','--quiet','--accept-license' -Wait
Remove-Item $out -Force -ErrorAction SilentlyContinue
`
	cmd := exec.Command("powershell", "-ExecutionPolicy", "Bypass", "-Command", ps)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func waitForDocker(timeoutSec int) bool {
	deadline := time.Now().Add(time.Duration(timeoutSec) * time.Second)
	for time.Now().Before(deadline) {
		if dockerRunning() {
			return true
		}
		time.Sleep(5 * time.Second)
		fmt.Print(".")
	}
	fmt.Println()
	return false
}

func waitForPort(addr string, timeoutSec int) bool {
	deadline := time.Now().Add(time.Duration(timeoutSec) * time.Second)
	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("tcp", addr, 2*time.Second)
		if err == nil {
			conn.Close()
			return true
		}
		time.Sleep(5 * time.Second)
	}
	return false
}

func status(msg string) {
	fmt.Printf("  >> %s\n", msg)
}

func ok(msg string) {
	fmt.Printf("  [OK] %s\n", msg)
}

func fatal(format string, args ...any) {
	fmt.Printf("  [ERROR] "+format+"\n", args...)
	waitExit()
	os.Exit(1)
}

func waitExit() {
	fmt.Println("\n  Press Enter to close.")
	fmt.Scanln()
}
